-- MySQL Script generated by MySQL Workbench
-- Sun Feb 26 12:03:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twitter_academy_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `twitter_academy_db` ;

-- -----------------------------------------------------
-- Schema twitter_academy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitter_academy_db` DEFAULT CHARACTER SET utf8 ;
USE `twitter_academy_db` ;

-- -----------------------------------------------------
-- Table `twitter_academy_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_academy_db`.`users` ;

CREATE TABLE IF NOT EXISTS `twitter_academy_db`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `banner` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verify` TINYINT NOT NULL DEFAULT 0,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `birthdate` DATE NULL,
  `gender` VARCHAR(5) NULL,
  `city` VARCHAR(255) NULL,
  `bio` VARCHAR(140) NULL,
  `register_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_follower` LONGTEXT NULL,
  `id_following` LONGTEXT NULL,
  `disabled` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_academy_db`.`tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_academy_db`.`tweet` ;

CREATE TABLE IF NOT EXISTS `twitter_academy_db`.`tweet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `message` VARCHAR(140) NOT NULL,
  `date_send` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_reply_tweet` INT(11) NULL,
  `id_retweet` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk0_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk0`
    FOREIGN KEY (`id_user`)
    REFERENCES `twitter_academy_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_academy_db`.`private_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_academy_db`.`private_message` ;

CREATE TABLE IF NOT EXISTS `twitter_academy_db`.`private_message` (
  `id_sender` INT(11) NOT NULL,
  `id_receiver` INT(11) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `date_send` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk1_idx` (`id_sender` ASC) VISIBLE,
  INDEX `fk2_idx` (`id_receiver` ASC) VISIBLE,
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_sender`)
    REFERENCES `twitter_academy_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2`
    FOREIGN KEY (`id_receiver`)
    REFERENCES `twitter_academy_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_academy_db`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_academy_db`.`likes` ;

CREATE TABLE IF NOT EXISTS `twitter_academy_db`.`likes` (
  `id_tweet` INT(11) NOT NULL,
  `id_user` INT(11) NOT NULL,
  INDEX `fk7_idx` (`id_tweet` ASC) VISIBLE,
  INDEX `fk8_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk3`
    FOREIGN KEY (`id_tweet`)
    REFERENCES `twitter_academy_db`.`tweet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk4`
    FOREIGN KEY (`id_user`)
    REFERENCES `twitter_academy_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
